apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-users
data:
  lb_auth_issuer_uri: http://127.30.148.152.31492
  lb_users_uri: http://127.30.148.152:31326
  port: "8001"
  db_host: "mysql8:3306"
  database: msvc_users
  course_url: "msvc-courses:8002"
  application.yaml: |-
    config:
      text: Configuration ambient por defect
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      text: Configuration ambient of dev
    ---
    spring:
          config:
            activate:
              on-profile: production
        config:
          text: Configuration ambient of production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-courses
data:
  port: "8002"
  db_host: "postgres15:5432"
  database: msvc_courses
  user_url: "msvc-users:8001"
