apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-courses
  strategy: {}
  template:
    metadata:
      labels:
        app: msvc-courses
    spec:
      containers:
        - image: naylu2418/courses:latest
          name: courses
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: password
            - name: USER_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: user_url
