apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres15
  template:
    metadata:
      labels:
        app: postgres15
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-courses
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-courses
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc

