spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}
      client:
        registration:
          users-client:
            provider: spring
            client-id: users-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USERS_URI:http://127.0.0.1:8001}/authorized
            scope: read
            client-name: users-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}